<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2061" started-at="2018-05-31T15:17:45Z" finished-at="2018-05-31T15:17:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2061" started-at="2018-05-31T15:17:45Z" finished-at="2018-05-31T15:17:47Z">
      <class name="com.test.Timeout">
        <test-method status="FAIL" signature="test1()[pri:0, instance:com.test.Timeout@1b604f19]" name="test1" duration-ms="2024" started-at="2018-05-31T15:17:45Z" finished-at="2018-05-31T15:17:47Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method com.test.Timeout.test1() didn't finish within the time-out 2000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.test.Timeout.test1() didn't finish within the time-out 2000
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- com.test.Timeout -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
